# Types

In [1]:
# data types

year_of_birth = 1994  #int
height_cm = 170.50  #float
subject = "Data Science"  #string
is_success = True  #boolean

print(type(year_of_birth), type(height_cm), type(subject), type(is_success))  #can check type

<class 'int'> <class 'float'> <class 'str'> <class 'bool'>


# Subsetting list

In [2]:
#create list, find subset, and slicee
# [start:end(not included):step(by how many)]

fruits = ["pineapple", "apple", "lemon", "strawberry", "orange", "kiwi"] # creates list called "friuts"
fruits[1]  # apple
fruits[0]  # "pineapple"
fruits[-1] # "kiwi"
fruits[5]  # "kiwi"
fruits[-3] # "strawberry"

# List slicing
fruits[::]    # ["pineapple", "apple", "lemon", "strawberry", "orange", "kiwi"]
fruits[0:2]   # ["pineapple", "apple"]
fruits[-2:-1] # ["orange"]
fruits[3:]    # ["strawberry", "orange", "kiwi"]
fruits[:4]    # ["pineapple", "apple", "lemon", "strawberry"]
fruits[:]     # ["pineapple", "apple", "lemon", "strawberry", "orange", "kiwi"]
fruits[::-1]  # ["kiwi", "orange", "strawberry", "lemon", "apple", "pineapple"]
fruits[::-2]  # ["kiwi", "strawberry", "apple"]
fruits[::2]   # ["pineapple", "lemon", "orange"]

# Understanding some default values
fruits[0:6:1]    # the same result as the result from fruits[::]
fruits[-1:-7:-1] # the same result as the result from fruits[::-1]

['kiwi', 'orange', 'strawberry', 'lemon', 'apple', 'pineapple']

In [3]:
print(fruits)

['pineapple', 'apple', 'lemon', 'strawberry', 'orange', 'kiwi']


In [4]:
print(fruits[0:-1:6])

['pineapple']


In [5]:
fruits

['pineapple', 'apple', 'lemon', 'strawberry', 'orange', 'kiwi']

# List Manipulation

In [6]:
# Add values to a list
fruits.append("peach")
fruits # ["pineapple", "apple", "lemon", "strawberry", "orange", "kiwi", "peach"]
fruits = fruits + ["fig", "melon"] # using + opperator
fruits # ["pineapple", "apple", "lemon", "strawberry", "orange", "kiwi", "peach", "fig", "melon"]

# Change values from a list
fruits[0:2] = ["grape", "mango"]
fruits # ["grape", "mango", "lemon", "strawberry", "orange", "kiwi", "peach", "fig", "melon"]

# Delete values from a list
fruits.remove("mango")
fruits # ["grape", "lemon", "strawberry", "orange", "kiwi", "peach", "fig", "melon"]

['grape', 'lemon', 'strawberry', 'orange', 'kiwi', 'peach', 'fig', 'melon']

In [7]:
# copy that also changes original

numbers = [10, 42, 28, 420]
numbers_copy = numbers
numbers_copy[2] = 100
numbers      # [10, 42, 100, 420]
numbers_copy # [10, 42, 100, 420]

# make copy without changing original

ratings = [4.5, 5.0, 3.5, 4.75, 4.00]
ratings_copy = ratings[:]
ratings_copy[0] = 2.0
ratings      # [4.5, 5.0, 3.5, 4.75, 4.0]
ratings_copy # [2.0, 5.0, 3.5, 4.75, 4.0]

# or

characters = ["A", "B", "C"]
characters_copy = list(characters)
characters_copy[-1] = "D"
characters      # ["A", "B", "C"]
characters_copy # ["A", "B", "D"]

['A', 'B', 'D']

# Dictionaries

In [8]:
# dictionary made with curly brackets
ratings = {
    "Ex Machina": 7.7,
    "Mad Max: Fury Road": 8.1,
    "1408" : 6.8
}

print(ratings["Ex Machina"]) # 7.7

7.7


In [9]:
ratings

{'Ex Machina': 7.7, 'Mad Max: Fury Road': 8.1, '1408': 6.8}

In [10]:
# add data
ratings["Deadpool"] = 8.0
print(ratings) # {'Ex Machina': 7.7, 'Mad Max: Fury Road': 8.1, '1408': 6.8, 'Deadpool': 8.0}

# update data
ratings["Ex Machina"] = 7.8
print(ratings) # {'Ex Machina': 7.8, 'Mad Max: Fury Road': 8.1, '1408': 6.8, 'Deadpool': 8.0}

# delete data
del(ratings["1408"])
print(ratings) # {'Ex Machina': 7.8, 'Mad Max: Fury Road': 8.1, 'Deadpool': 8.0}

{'Ex Machina': 7.7, 'Mad Max: Fury Road': 8.1, '1408': 6.8, 'Deadpool': 8.0}
{'Ex Machina': 7.8, 'Mad Max: Fury Road': 8.1, '1408': 6.8, 'Deadpool': 8.0}
{'Ex Machina': 7.8, 'Mad Max: Fury Road': 8.1, 'Deadpool': 8.0}


In [11]:
# check if data is in dictionary
print("Ex Machina" in ratings) # True

True


# Functions

In [12]:
# make functionswith def to solve specific task if not already included in python
#funcions included: max(iterable [, key]), , min(iterable [, key]), type(object), round(number [, ndigits])
# We can use the function help([object]) or ?function_name to see the documentation of any function.

def is_prime(n):
    if n <= 1:
        return False
    elif n <= 3:
        return True
    elif n % 2 == 0 or n % 3 == 0:
        return False
    current_number = 5
    while current_number * current_number <= n:
        if n % current_number == 0 or n % (current_number + 2) == 0:
            return False
        current_number = current_number + 6
    return True

# Methods

In [13]:

# String methods
text = "Data Science" 
text.upper() # "DATA SCIENCE"
text.lower() # "data science"
text.capitalize() # "Data science"

# Lists methods
numbers = [1, 4, 0, 2, 9, 9, 10]
numbers.reverse()
print(numbers) # [10, 9, 9, 2, 0, 4, 1]
numbers.sort()
print(numbers) # [0, 1, 2, 4, 9, 9, 10]

# Dictionaris methods
ratings = {
    "Ex Machina": 7.7,
    "Mad Max: Fury Road": 8.1,
    "1408" : 6.8
}

print(ratings.keys()) # dict_keys(['Ex Machina', 'Mad Max: Fury Road', '1408'])
print(ratings.values()) # dict_values([7.7, 8.1, 6.8])
print(ratings.items()) # dict_items([('Ex Machina', 7.7), ('Mad Max: Fury Road', 8.1), ('1408', 6.8)])

[10, 9, 9, 2, 0, 4, 1]
[0, 1, 2, 4, 9, 9, 10]
dict_keys(['Ex Machina', 'Mad Max: Fury Road', '1408'])
dict_values([7.7, 8.1, 6.8])
dict_items([('Ex Machina', 7.7), ('Mad Max: Fury Road', 8.1), ('1408', 6.8)])


In [14]:
numbers = [10, 30, 55, 40, 8, 30, 30]
text = "Data Science"

print(numbers.index(55))  # 4
print(text.index("i"))   # 1

print(numbers.count(30)) # 2
print(text.count("a"))   # 1

2
7
3
2


# NumPy

In [15]:
import numpy as np

# NumPy Array — Type Converting

np.array([False, 42, "Data Science"])       # array(["False", "42", "Data Science"], dtype="<U12")
np.array([False, 42], dtype = int)          # array([ 0, 42])
np.array([False, 42, 53.99], dtype = float) # array([  0.  ,  42.  ,  53.99])


array([ 0.  , 42.  , 53.99])

In [16]:
# Operators on np.array


np.array([37, 48, 50]) + 1 # array([38, 49, 51])
np.array([20, 30, 40]) * 2 # array([40, 60, 80])
np.array([42, 10, 60]) / 2 # array([ 21.,   5.,  30.])

np.array([1, 2, 3]) * np.array([10, 20, 30]) # array([10, 40, 90])
np.array([1, 2, 3]) - np.array([10, 20, 30]) # array([ -9, -18, -27])

array([ -9, -18, -27])

In [17]:
# Subsetting 2-dimensional arrays

numbers = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

numbers[2, 1]     # 8
numbers[-1, 0]    # 10
numbers[0]        # array([1, 2, 3])
numbers[:, 0]     # array([ 1,  4,  7, 10])
numbers[0:3, 2]   # array([3, 6, 9])
numbers[1:3, 1:3] # array([[5, 6],[8, 9]])

array([[5, 6],
       [8, 9]])

In [18]:
# check shape of array

numbers = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12],
    [13, 14, 15]
])

numbers.shape # (5, 3)

(5, 3)

# basic stats

In [19]:
learning_hours = [1, 2, 6, 4, 10]
grades = [3, 4, 6, 5, 6]

np.mean(learning_hours)   # 4.6 = average
np.median(learning_hours) # 4.0 = middle number or if even avg of middle #
np.std(learning_hours)    # 3.2 = standard deviation
np.corrcoef(learning_hours, grades) # [[ 1.          0.88964891][ 0.88964891  1.        ]] = to see if there is correlation

array([[1.        , 0.88964891],
       [0.88964891, 1.        ]])

# Loops and iterables

In [20]:
# simple "for" loop 

numbers = [10, 12, 15, 18, 20]
for number in numbers:
    print(number)

10
12
15
18
20


In [21]:
# lists strings and tuples

numbers = [10, 12, 15, 18, 20]  # list
fruits = ("apple", "pineapple", "blueberry")  #tuple
message = "I love Python ❤️"  #string



# Element access using integer indices
print(numbers[0])
print(fruits[2])
print(message[-2])

10
blueberry
❤


In [22]:
# Slicing the sequences
print(numbers[:2])
print(fruits[1:])
print(message[2:])

[10, 12]
('pineapple', 'blueberry')
love Python ❤️


In [23]:
# other iterables Sets, Dictionaries, Files, and Generators.

my_set = {2, 3, 5}
my_dict = {"name": "Ventsislav", "age": 24}
my_file = open("example.txt")
squares = (n**2 for n in my_set)

In [24]:
# using "while" only create index for lists

index = 0
numbers = [1, 2, 3, 4, 5]
while index < len(numbers):
    print(numbers[index])
    index += 1

1
2
3
4
5


In [25]:
# using "for" to create index for dict objects

numbers = {1, 2, 3, 4, 5}
for number in numbers:
    print(number)

1
2
3
4
5


# iterators

In [26]:
# create iterator with "iter"
numbers = [10, 12, 15, 18, 20]
fruits = ("apple", "pineapple", "blueberry")
message = "I love Python ❤️"

print(iter(numbers))
print(iter(fruits))
print(iter(message))

In [27]:
# "next() returnd succesive item from list"
values = [10, 20, 30, 40]
iterator = iter(values)

print(next(iterator))
print(next(iterator))
print(next(iterator))
print(next(iterator))

10
20
30
40


In [28]:
# define a function that loops through an iterable without using a for loop.

def custom_for_loop(iterable, action_to_do):
    iterator = iter(iterable)
    done_looping = False
    while not done_looping:
        try:
            item = next(iterator)
        except StopIteration:
            done_looping = True
        else:
            action_to_do(item)
            

# Using the function above

numbers = {1, 2, 3, 4, 5}
custom_for_loop(numbers, print)


1
2
3
4
5


In [29]:
numbers = [100, 200, 300]
iterator1 = iter(numbers)
iterator2 = iter(iterator1)

# Check if they are the same object
print(iterator1 is iterator2)

for number in iterator1:
    print(number)

True
100
200
300


In [30]:
# enumerate example
fruits = ("apple", "pineapple", "blueberry")
iterator = enumerate(fruits)
print(type(iterator))
print(next(iterator))

<class 'enumerate'>
(0, 'apple')


In [31]:
# reversed example
fruits = ("apple", "pineapple", "blueberry")
iterator = reversed(fruits)
print(type(iterator))
print(next(iterator))

<class 'reversed'>
blueberry


In [32]:
# zip example
numbers = [1, 2, 3]
squares = [1, 4, 9]
iterator = zip(numbers, squares)
print(type(iterator))
print(next(iterator))
print(next(iterator))

<class 'zip'>
(1, 1)
(2, 4)


In [33]:
# map example
numbers = [1, 2, 3, 4, 5]
squared = map(lambda x: x**2, numbers)
print(type(squared))
print(next(squared))
print(next(squared))

<class 'map'>
1
4


In [34]:
# filter example

numbers = [-1, -2, 3, -4, 5]
positive = filter(lambda x: x > 0, numbers)
print(type(positive))
print(next(positive))

<class 'filter'>
3


In [35]:
# fie is also iterator

file = open("example.txt")
print(type(file))
print(next(file))
print(next(file))
print(next(file))
file.close()

<class '_io.TextIOWrapper'>
This is some example text for python projec basic

i am testing this to see if it workes

adding a new line to see if wont get stop iteration


In [36]:
# iterate over key-value pairs of a Python dictionary using the items() method
my_dict = {"name": "Armando", "age": 37}
iterator = my_dict.items()
print(type(iterator))
for key, item in iterator:
    print(key, item)

<class 'dict_items'>
name Armando
age 37


In [37]:
import pandas as pd  # to read_csv

# load the data in chunks, then perform the desired operation/s on each chunk

# Initialize an empty dictionary
counts_dict = {}

# Iterate over the file chunk by chunk
for chunk in pd.read_csv("iris.csv", chunksize = 10):
    # Iterate over the "species" column in DataFrame
    for entry in chunk["species"]:
        if entry in counts_dict.keys():
            counts_dict[entry] += 1
        else:
            counts_dict[entry] = 1

# Print the populated dictionary
print(counts_dict)

{'Iris-setosa': 50, 'Iris-versicolor': 50, 'Iris-virginica': 50}


In [38]:
# custom iterator (not ideal)

class generate_numbers:
    def __init__(self, min_value, max_value):
        self.current = min_value
        self.high = max_value

    def __iter__(self):
        return self

    def __next__(self):
        if self.current > self.high:
            raise StopIteration
        else:
            self.current += 1
            return self.current - 1

numbers = generate_numbers(40, 50)
print(type(numbers))
print(next(numbers))
print(next(numbers))
print(next(numbers))

<class '__main__.generate_numbers'>
40
41
42


In [39]:
# recreate custome iterator above with generate_numbers and yeild expression (better way!)

def generate_numbers(min_value, max_value):
    while min_value < max_value:
        yield min_value
        min_value += 1

numbers = generate_numbers(10, 20)
print(type(numbers))
print(next(numbers))
print(next(numbers))
print(next(numbers))

<class 'generator'>
10
11
12


In [40]:
# The general formula is:
# (output expression "for" iterator variable "in" iterable)

numbers = [1, 2, 3, 4, 5]
squares = (number**2 for number in numbers)
print(type(squares))
print(next(squares))
print(next(squares))
print(next(squares))

<class 'generator'>
1
4
9


In [41]:
# add a conditional expression on the iterable

numbers = [1, 2, 3, 4, 5]
squares = (number**2 for number in numbers if number % 2 == 0)
print(type(squares))
print(list(squares))

<class 'generator'>
[4, 16]


In [42]:
# multiple conditional expressions on the iterable for more complex filtering

numbers = [1, 2, 3, 4, 5]
squares = (number**2 for number in numbers if number % 2 == 0 if number % 4 == 0)
print(type(squares))
print(list(squares))

<class 'generator'>
[16]


In [43]:
# add an if-else clause on the output expression 

numbers = [1, 2, 3, 4, 5]
result = ("even" if number % 2 == 0 else "odd" for number in numbers)
print(type(result))
print(list(result))

<class 'generator'>
['odd', 'even', 'odd', 'even', 'odd']


# list comprehension

In [44]:
# The components of a list comprehension are: Output Expression (Optional), Iterable, Iterator variable which represents the members of the iterable

numbers = [1, 2, 3, 4, 5]
squares = [number**2 for number in numbers]
print(squares)

[1, 4, 9, 16, 25]


In [45]:
# advanced list comprehensions which include a conditional statement on the iterable.

numbers = [1, 2, 3, 4, 5]
squares = [number**2 for number in numbers if number > 2]
print(squares)

[9, 16, 25]


In [46]:
# comprehension using for loop (not iedeal compared to above)

numbers = [1, 2, 3, 4, 5]
squares = []
for number in numbers:
    if number > 2:
        squares.append(number**2)
print(squares)

[9, 16, 25]


In [47]:
#"for" loop vs list comprehension computatuinal speed usig timeit

import timeit

def squares(size):
    result = []
    for number in range(size):
        result.append(number*number)
    return result

def squares_comprehension(size):
    return [number*number for number in range(size)]

print(timeit.timeit("squares(50)", "from __main__ import squares", number = 1_000_000))
print(timeit.timeit("squares_comprehension(50)", "from __main__ import squares_comprehension", number = 1_000_000))


5.4619700999999985
3.0684547000000038


In [48]:
# lambda functions are passed as parameters to functions which expect a function object as one of their parameters like map and filter

# Map
numbers = [1, 2, 3, 4, 5]
squares = list(map(lambda x: x**2, numbers))
print(squares)

# List Comprehension
numbers = [1, 2, 3, 4, 5]
squares = [number**2 for number in numbers]
print(squares)

[1, 4, 9, 16, 25]
[1, 4, 9, 16, 25]


In [49]:
#The filter function constructs an iterator from elements of iterable for which the passed function returns true

# Filter
numbers = [1, 2, 3, 4, 5]
filtered = list(filter(lambda x: x % 2 == 0, numbers))
print(filtered)

# List Comprehension
numbers = [1, 2, 3, 4, 5]
filtered = [number for number in numbers if number % 2 == 0]
print(filtered)

[2, 4]
[2, 4]


# more complex list comprehension

In [50]:
# many contitionl statements on iterable
# output expression for item in iterable if conditions

numbers = [1, 2, 3, 4, 5, 6, 18, 20]
squares = [number for number in numbers if number % 2 == 0 if number % 3 == 0]
print(squares)

[6, 18]


In [51]:
# if-else clause on the output expression
# output expression if/elde statement for itmens in iterable if conditions on iterable

numbers = [1, 2, 3, 4, 5, 6, 18, 20]
squares = ["small" if number < 10 else "big" for number in numbers if number % 2 == 0 if number % 3 == 0]
print(squares)

['small', 'big']


In [52]:
# above can also be written like this for more readablilty

numbers = [1, 2, 3, 4, 5, 6, 18, 20]
squares = [
    "small" if number < 10 else "big" 
    for number in numbers 
    if number % 2 == 0 
    if number % 3 == 0]
print(squares)

['small', 'big']


# nested for loops

In [53]:
#using for loops to flatten matrix

matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

flattened = []
for row in matrix:
    for item in row:
        flattened.append(item)
        
print(flattened)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [54]:
# same thing can be done using list comprehensoin

matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
flattened = [item for row in matrix for item in row]        
print(flattened)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


# nested list comprehension

In [55]:
# if we place a list comprehension in the output expression of another list comprehension, we’ll get a matrix as result.

matrix = [[item for item in range(5)] for row in range(3)]
print(matrix)

[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]


# other comprehensions

In [56]:
# dictiopnary comprehensions

prices = {"beer": 2, "fish": 5, "apple": 1}
float_prices = {key:float(value) for key, value in prices.items()}
print(float_prices)

{'beer': 2.0, 'fish': 5.0, 'apple': 1.0}


In [57]:
# set comprehensions

numbers = [10, 10, 20, 30, 12, -20, 0, 1]
unique_squares = {number**2 for number in numbers}
print(unique_squares)

{0, 1, 900, 100, 400, 144}
